const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Behaviors.Orbit,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Solid: 0},
	{ground1: 0},
	{platform: 0},
	{ground3: 0},
	{ground2: 0},
	{life: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{player: 0},
	{Keyboard: 0},
	{Rotate: 0},
	{Tween: 0},
	{coin: 0},
	{riverbackground: 0},
	{Sine: 0},
	{Jumpthru: 0},
	{shortBridge: 0},
	{river: 0},
	{bridge: 0},
	{portalLvl1: 0},
	{Audio: 0},
	{ScoreVar: 0},
	{Anchor: 0},
	{ScoreDisplay: 0},
	{coinDisplay: 0},
	{HeartLive: 0},
	{HeartGain: 0},
	{RiverRestart: 0},
	{Particlesbridge: 0},
	{TiledBackground3: 0},
	{loadingbox: 0},
	{loadingTxt: 0},
	{loadingpanda: 0},
	{TiledBackground: 0},
	{gothrough: 0},
	{Sprite: 0},
	{piranha: 0},
	{cactusSpike: 0},
	{portalLvl2: 0},
	{cactusMan: 0},
	{Orbit: 0},
	{spinningVine: 0},
	{TiledBackground2: 0},
	{Bullet: 0},
	{rock: 0},
	{spawnpoint: 0},
	{loadingbar: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{loadBtn: 0},
	{playBtn: 0},
	{loadingbox2: 0},
	{Sprite5: 0},
	{loadlbl: 0},
	{loadlbl2: 0},
	{loadingBARbackground: 0},
	{Sprite3: 0},
	{portalLvl3: 0},
	{TiledBackground4: 0},
	{saveBtn: 0},
	{loadBtn2: 0},
	{GameSavedTxt: 0},
	{bossBG: 0},
	{MoveTo: 0},
	{monster: 0},
	{loadBtn3: 0},
	{Fade: 0},
	{arrow: 0},
	{playerHealthChar: 0},
	{Sprite6: 0},
	{PLYhealthBG: 0},
	{MONShealthBG: 0},
	{playHealthVar: 0},
	{PLYhealthCOLOR: 0},
	{MonsHealthVar: 0},
	{MONShealthcolor: 0},
	{Sprite7: 0},
	{Particles: 0},
	{WinBG: 0},
	{layout: 0},
	{loading: 0}
];

self.InstanceType = {
	background: class extends self.ITiledBackgroundInstance {},
	ground1: class extends self.ITiledBackgroundInstance {},
	platform: class extends self.ITiledBackgroundInstance {},
	ground3: class extends self.ITiledBackgroundInstance {},
	ground2: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	coin: class extends self.ISpriteInstance {},
	riverbackground: class extends self.ITiledBackgroundInstance {},
	shortBridge: class extends self.ISpriteInstance {},
	river: class extends self.ISpriteInstance {},
	bridge: class extends self.ISpriteInstance {},
	portalLvl1: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	ScoreDisplay: class extends self.ITextInstance {},
	coinDisplay: class extends self.ISpriteInstance {},
	HeartLive: class extends self.ITiledBackgroundInstance {},
	HeartGain: class extends self.ISpriteInstance {},
	RiverRestart: class extends self.ISpriteInstance {},
	Particlesbridge: class extends self.IParticlesInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	loadingbox: class extends self.ISpriteInstance {},
	loadingTxt: class extends self.ITextInstance {},
	loadingpanda: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	gothrough: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	piranha: class extends self.ISpriteInstance {},
	cactusSpike: class extends self.ISpriteInstance {},
	portalLvl2: class extends self.ISpriteInstance {},
	cactusMan: class extends self.ISpriteInstance {},
	spinningVine: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	rock: class extends self.ISpriteInstance {},
	spawnpoint: class extends self.ISpriteInstance {},
	loadingbar: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	loadBtn: class extends self.ISpriteInstance {},
	playBtn: class extends self.ISpriteInstance {},
	loadingbox2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	loadlbl: class extends self.ITextInstance {},
	loadlbl2: class extends self.ITextInstance {},
	loadingBARbackground: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	portalLvl3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	saveBtn: class extends self.ISpriteInstance {},
	loadBtn2: class extends self.ISpriteInstance {},
	GameSavedTxt: class extends self.ITextInstance {},
	bossBG: class extends self.ITiledBackgroundInstance {},
	monster: class extends self.ISpriteInstance {},
	loadBtn3: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	playerHealthChar: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PLYhealthBG: class extends self.ISpriteInstance {},
	MONShealthBG: class extends self.ISpriteInstance {},
	PLYhealthCOLOR: class extends self.ISpriteInstance {},
	MONShealthcolor: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	WinBG: class extends self.ITiledBackgroundInstance {}
}